namespace NotificationService.Api.Controllers;

using Microsoft.AspNetCore.Mvc;
using NotificationService.Api.Models.Requests;
using NotificationService.Api.Models.Responses;

/// <summary>
/// Endpoints used by internal services (e.g. authentication) to trigger
/// verification code delivery to users.
/// </summary>
[ApiController]
[Route("api/notifications")]
public class VerificationController : ControllerBase
{
    private readonly ILogger<VerificationController> _logger;

    public VerificationController(ILogger<VerificationController> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Receives a verification code generated by the authentication service so that
    /// the notification service can deliver it (e.g. via email or push).
    /// 
    /// For now, this implementation logs the request and returns 202 Accepted so
    /// that the integration between auth-service and notification-service can be
    /// tested end-to-end without requiring a full email pipeline.
    /// </summary>
    /// <param name="request">Verification payload.</param>
    /// <response code="202">Verification request accepted for processing.</response>
    /// <response code="400">Invalid request payload.</response>
    [HttpPost("send-code")]
    [ProducesResponseType(StatusCodes.Status202Accepted)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    public IActionResult SendCode([FromBody] SendCodeRequest request)
    {
        if (request == null)
        {
            return BadRequest(new ErrorResponse
            {
                Error = "ValidationError",
                Message = "Request body is required.",
                Timestamp = DateTime.UtcNow
            });
        }

        if (request.UserId == Guid.Empty)
        {
            return BadRequest(new ErrorResponse
            {
                Error = "ValidationError",
                Message = "UserId is required.",
                Timestamp = DateTime.UtcNow
            });
        }

        if (string.IsNullOrWhiteSpace(request.Email))
        {
            return BadRequest(new ErrorResponse
            {
                Error = "ValidationError",
                Message = "Email is required.",
                Timestamp = DateTime.UtcNow
            });
        }

        if (string.IsNullOrWhiteSpace(request.Code))
        {
            return BadRequest(new ErrorResponse
            {
                Error = "ValidationError",
                Message = "Code is required.",
                Timestamp = DateTime.UtcNow
            });
        }

        if (string.IsNullOrWhiteSpace(request.Type))
        {
            return BadRequest(new ErrorResponse
            {
                Error = "ValidationError",
                Message = "Type is required.",
                Timestamp = DateTime.UtcNow
            });
        }

        _logger.LogInformation(
            "Received verification code from auth-service. UserId={UserId}, Email={Email}, Type={Type}, Timestamp={Timestamp}",
            request.UserId,
            request.Email,
            request.Type,
            request.Timestamp);

        // In a future iteration, this is where we would enqueue a background job
        // or call an email service / push notification provider to actually send
        // the verification code to the user.

        return Accepted(new
        {
            message = "Verification code accepted for processing.",
            userId = request.UserId,
            type = request.Type,
            timestamp = DateTime.UtcNow
        });
    }
}

